Controllers/ActivityController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ActivityTracker.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;


namespace ActivityTracker.Controllers
{
    public class ActivityController : Controller
    {

        private ActivityContext _context;
        public ActivityController(ActivityContext context){
            _context = context;
        }

        public IActionResult Delete(int id){
            int? UserID = HttpContext.Session.GetInt32("LogedUserID");
            
            if(UserID != null){
                Person user = _context.Users.SingleOrDefault(u => u.UserID == UserID);

                MyActivity activity = _context.Activities.SingleOrDefault(act => act.ActivityID == id);

                if(activity.User == user){
                    _context.Remove(activity);
                    _context.SaveChanges();
                }
            }
            return RedirectToAction("Activities", "Home");
        }


        public IActionResult Join(int id){
            // TempData["busy"] = "";
            int? UserID = HttpContext.Session.GetInt32("LogedUserID");
            
            if(UserID != null){
                Person user = _context.Users.SingleOrDefault(u => u.UserID == UserID);

                MyActivity activity = _context.Activities.SingleOrDefault(act => act.ActivityID == id);

                UserActivity userActivity = new UserActivity(){
                    User = user,
                    Activity = activity
                };

                List<UserActivity> otherActivities = _context.UsersActivities
                .Include(uAct => uAct.User)
                .Include(uAct => uAct.Activity)
                .Where(uAct => uAct.User == user)
                .ToList();
                
                bool busy = false;
                foreach(var act in otherActivities){
                    
                    if(act.Activity.ActivityDate == activity.ActivityDate){
                        busy = true;
                    }
                }
                if(busy){
                    // TempData["busy"] = ":Looks like you already have something scheduled for this date";
                    return RedirectToAction("Activities", "Home");
                }

                user.UserActivity.Add(userActivity);
                activity.UserActivity.Add(userActivity);
                _context.Add(userActivity);
                _context.SaveChanges();
            }
            
            return RedirectToAction("Activities", "Home");
        }

        public IActionResult Leave(int id){
            int? UserID = HttpContext.Session.GetInt32("LogedUserID");
            
            if(UserID != null){
                Person user = _context.Users.SingleOrDefault(u => u.UserID == UserID);

                UserActivity userActivity = _context.UsersActivities.SingleOrDefault(uact => uact.UserActivityID == id);

                if(userActivity.User == user){
                    _context.Remove(userActivity);
                    _context.SaveChanges();
                }
            }
            return RedirectToAction("Activities", "Home");
        }
        
        public IActionResult AddNewActivity(){
            return View();
        }

        public IActionResult CreateActivity(MyActivity activity, string timetype){
            int? UserID = HttpContext.Session.GetInt32("LogedUserID");
            
            if(UserID != null){
                Person user = _context.Users.SingleOrDefault(u => u.UserID == UserID);
                
                if(ModelState.IsValid && activity.ActivityDate > DateTime.Now){
                    activity.User = user;
                    activity.Duration += " " + timetype; 
                    _context.Add(activity);
                    user.myActivity.Add(activity);
                    _context.SaveChanges();
                }
                else{
                    if(activity.ActivityDate < DateTime.Now){
                        ViewBag.error = "Please enter a date in future";
                        return View("AddNewActivity");
                    }
                    return View("AddNewActivity");
                }

            }
            return RedirectToAction("ActivityInfo", new{id = activity.ActivityID});
        }

        public IActionResult ActivityInfo(int id){
            int? UserID = HttpContext.Session.GetInt32("LogedUserID");
            
            if(UserID != null){
                Person user = _context.Users.SingleOrDefault(u => u.UserID == UserID);
                
                MyActivity activity = _context.Activities.Include(act => act.User).SingleOrDefault(act => act.ActivityID == id);
                if(activity == null){
                    return RedirectToAction("Index", "Home");
                }

                List<UserActivity> allUserActivities = _context.UsersActivities
                    .Include(userAct => userAct.User)
                    .Include(userAct => userAct.Activity)
                    .ToList();
                ViewBag.allUserActivities = allUserActivities;
                ViewBag.activity = activity;
                ViewBag.user = user;
                
                return View();
            }
            return RedirectToAction("Index", "Home");
                
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ActivityTracker.Models;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace ActivityTracker.Controllers
{
    public class HomeController : Controller
    {

        private ActivityContext _context;
        public HomeController(ActivityContext context){
            _context = context;
        }


        public IActionResult Index(){
            int? UserID = HttpContext.Session.GetInt32("LogedUserID");
            
            if(UserID != null){
                return RedirectToAction("Activities");
            }
            
            return View();
        }

        public IActionResult Activities()
        {
            int? UserID = HttpContext.Session.GetInt32("LogedUserID");
            
            if(UserID == null){
                HttpContext.Session.Clear();
                return RedirectToAction("Index");
            }
           
            Person user = _context.Users.SingleOrDefault(u => u.UserID == UserID);
            ViewBag.user = user; 

            List<MyActivity> activities = _context.Activities
                .Include(act => act.User)
                .Where(act => act.ActivityDate>DateTime.Now)
                .OrderByDescending(msg => msg.CreatedAt)
                .ToList();
            ViewBag.allActivities = activities;

            List<UserActivity> userActivity = _context.UsersActivities
            .Include(uact => uact.User)
            .Include(uact => uact.Activity)
            .ToList();
            ViewBag.userActivity = userActivity;

            return View();
        }


public IActionResult Create(Person person, string ConfirmPass){

            ViewBag.error ="";

            if(ModelState.IsValid && person.Password == ConfirmPass){
                PasswordHasher<Person> Hasher = new PasswordHasher<Person>();
                person.Password = Hasher.HashPassword(person, person.Password);
                //Save your user object to the database
                _context.Add(person);
                _context.SaveChanges();

                Person ReturnedValue = _context.Users.SingleOrDefault(u => u.Email == person.Email); 

                HttpContext.Session.SetInt32("LogedUserID", ReturnedValue.UserID);
                
                return RedirectToAction("Activities");
            }
            else{
                if(person.Password != ConfirmPass){
                    ViewBag.error = "Password did not match";
                }
                return View("Index");
            }
        }



       public IActionResult LogOff(){
            HttpContext.Session.Clear();
            return RedirectToAction("Index");
        }

        public IActionResult LogIn(string Email, string Password){
            ViewBag.error ="";

            Person dbUser = _context.Users.SingleOrDefault(u => u.Email == Email);           
            if(dbUser != null){
                var Hasher = new PasswordHasher<Person>();
                // Pass the user object, the hashed password, and the PasswordToCheck
                if(0 != Hasher.VerifyHashedPassword(dbUser, dbUser.Password, Password))
                {
                    //Handle success
                    HttpContext.Session.SetInt32("LogedUserID", dbUser.UserID);
                    return RedirectToAction("Activities");
                }
                else{
                    ViewBag.error = "Please check the password or email";
                    return View("Index");
                }
            }
            else{
                ViewBag.error = "Please check the password or email";
                return View("Index");
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Home/Activities.cshtml
@{
    ViewData["Title"] = "Contact";
}

<div>
    <h1>Welcome to Activity Tracker</h1>
    <table>
        <tr>
            <th>Activity</th>
            <th>Date and Time</th>
            <th>Duration</th>
            <th>Event Coordinator</th>
            <th>Number of Participants</th>
            <th>Action</th>
        </tr>
        @foreach(var activity in @ViewBag.allActivities){
            <tr>
                <td><a asp-area="" asp-controller="Activity" asp-action="ActivityInfo" asp-route-id="@activity.ActivityID">@activity.Title</a></td>
                <td>@activity.ActivityDate.ToString("dd/MM/yyyy") at @activity.Time</td>
                <td>@activity.Duration</td>
                <td>@activity.User.FirstName</td>
                <td>@activity.UserActivity.Count</td>
                
                
                @if(@activity.User == @ViewBag.user){
                    <td><a asp-area="" asp-controller="Activity" asp-action="Delete" asp-route-id="@activity.ActivityID">Delete</a></td>
                }
                else{ 
                    bool contains = false;
                    int registryId = 0;
                    
                    @foreach(var uact in @ViewBag.userActivity){
                        @if(uact.Activity == @activity && @ViewBag.user == uact.User){
                            contains = true;
                            registryId = uact.UserActivityID;
                            break;
                        }
                    }

                    @if(contains){
                        <td><a asp-area="" asp-controller="Activity" asp-action="Leave" asp-route-id="@registryId">Leave</a></td>
                    }
                    else{
                        <td><a asp-area="" asp-controller="Activity" asp-action="Join" asp-route-id="@activity.ActivityID">Join</a></td>
                    }
                }
                

            </tr>
        }
    </table>
    
    <br>
    <a asp-area="" asp-controller="Activity" asp-action="AddNewActivity"><button>Add a Activity</button></a>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="top-spacing">
    <h1>Welcome to Activity Tracker</h1>
    
    <div class="half">
       
    
        <form asp-action="LogIn" asp-controler="Home" method="POST">
            <label for="Email">Email:</label>
            <input type="text" name="Email">
            <br>
    
            <label for="Password">Password:</label>
            <input type="password" name="Password">
            <br>
    
            <input type="submit" value="Sign in">
        </form>
        
        <p>@ViewBag.error</p>
    
    </div>


    <div class="half">
        @model Person
        <form asp-action="Create" asp-controller="Home" method="POST">
            <span asp-validation-for="FirstName"></span>
            <label asp-for="FirstName">First Name:</label>
            <input type="text" asp-for="FirstName">
            <br>

            <span asp-validation-for="LastName"></span>
            <label asp-for="LastName">Last Name:</label>
            <input type="text" asp-for="LastName">
            <br>

            <span asp-validation-for="Email"></span>
            <label asp-for="Email">Email:</label>
            <input type="text" asp-for="Email">
            <br>
            
            <span asp-validation-for="Password"></span>
            <label asp-for="Password">Password:</label>
            <input type="Password" asp-for="Password">
            <br>
                
            <span>@ViewBag.error</span>
            <label for="ConfirmPass">Confirm Password:</label>
            <input type="password" name="ConfirmPass">
            <br>

            <input type="submit" value="Register">
        </form>
    </div>

</div>